api_platform:
    mapping:
        paths: 
             - '%kernel.project_dir%/src/Entity'
             - '%kernel.project_dir%/config/api_platform/resources'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Autorization
                type: header
    title: 'Library API'
    description: 'API library catalogue'
    version: 1.0
    show_webby: false
    formats:
            json:
                mime_types: ['application/json']
            jsonld:
                mime_types: ['application/ld+json']
            html:
                mime_types: ['text/html']
    # The list of enabled error formats. The first one will be the default.
    error_formats:
        jsonproblem:
            mime_types: ['application/problem+json']
        jsonld:
            mime_types: ['application/ld+json']